version: "3.9"

services:
  storefront: 
    build: .
  database: 
    image: "mysql"
    env_file:
      - ./mysql/env_vars
    volumes: # mount the sql scripts to the container
      - ./mysql:/docker-entrypoint-initdb.d:ro # source:target:access mode ro = read only rw = read write